# Calculations for Results Tables

The code below will perform the calculations to make the data tables presented in the class handout.

First, we will calculate values of $k_H/k_a$ and values for $pK_a$ from the `results.csv` file.  We will write the edited results to a file called `results2.csv` and use that text in making the data table in the handout.

Then we will calculate the same values from the author's data in table 1 of the paper.  the data has been entered into a file named `Table1data.csv`.  Take note that a typographical error was identified in the table and corrected (molecule **1f** has a $k_{AR}$ for $pH = 1.0$ reported as $7.83\times 10^{-4}~s^{-1}$ and the correct value was judged to be $7.83\times 10^{-5}~s^{-1}$)

Table 1 is found in "On the Rearrangement in Dioxane/Water of (*Z*)-Arylhydrazones of 5-Amino-3-benzoyl-1,2,4-oxadiazole into (2-Aryl-5-phenyl-2*H*-1,2,3-triazol-4-yl)ureas: Substituent Effects on the Different Reaction Pathways." F. D'Anna, V. Frenna, G. Macaluso, S. Marullo, S. Morganti, V. Pace, D. Spinelli, R. Spisani, C. Tavani, *J. Org. Chem.*, **2006**, *71*, 5616-5624. https://doi.org/10.1021/jo0605849

In [ ]:
##############################################################
### Set up libraries and global variables
##############################################################

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import scipy.constants as constants  # a collection of scientific constants
from scipy.optimize import curve_fit


github_location = "https://raw.githubusercontent.com/blinkletter/4410PythonNotebooks/main/Class_23/data/"
github_location = "./"
github_location_styles = "https://raw.githubusercontent.com/blinkletter/LFER-QSAR/main/styles/"
github_location_LFER_tables = "https://raw.githubusercontent.com/blinkletter/LFER-QSAR/main/data/"

datafile_name = "results.csv"

##############################################################
### Read data for thermodynamic parameters
##############################################################

df = pd.read_csv(github_location + datafile_name, 
             delimiter = ",", 
             skipinitialspace=True, 
             index_col="Substituent", 
             comment = "#") 
display(df)

df2 = df[["molecule","kOH","kH2O","kHKa"]].copy()
df2["pKa"]=-np.log10(df["Ka"])

if True:   # add text for LaTeX
    df2["molecule"]="\textbf{"+df2["molecule"]+"}"    # add LaTeX code for use in table in LaTeX document
    df2.index = "\ce{"+df2.index+"}"
    df2["kH2O x 10^6"] = df2["kH2O"] * 1E6
    df2["kH/Ka x 10^3"]=df2["kHKa"] * 1E3

#print(df["kH2O"])
df3 = df2[["molecule","kOH","kH2O x 10^6","kH/Ka x 10^3","pKa"]].copy()
df3.to_csv("results2.csv")
df3

,sigma,s_plus,s_minus,file,molecule,Ka,kOH,kH2O,kHKa,Ka_sd,kOH_sd,kH2O_sd,kHKa_sd
Substituent,,,,,,,,,,,,,
p-OCH3,-0.27,-0.78,-0.26,1c-data.csv,1c,0.4682,2.177,1.245000e-05,0.004986,0.07780,0.06324,4.121000e-07,0.000263
p-CH3,-0.17,-0.31,-0.17,1e-data.csv,1e,0.4525,1.564,1.197000e-05,0.004350,0.05586,0.03957,3.419000e-07,0.000197
m-CH3,-0.07,-0.07,-0.07,1d-data.csv,1d,0.5912,1.368,8.776000e-06,0.003500,0.09015,0.03981,3.292000e-07,0.000154
H,0.00,0.00,0.00,1b-data.csv,1b,0.5597,1.311,6.620000e-06,0.003410,0.10010,0.04700,3.460000e-07,0.000224
p-Br,0.23,0.15,0.25,1i-data.csv,1i,0.9740,7.726,3.287000e-06,0.000986,0.33660,0.35250,2.021000e-07,0.000079
p-Cl,0.23,0.11,0.19,1g-data.csv,1g,0.8076,6.306,3.822000e-06,0.001192,0.23160,0.28140,2.267000e-07,0.000084
m-Cl,0.37,0.37,0.37,1f-data.csv,1f,1.0240,10.730,2.539000e-06,0.000759,0.29720,0.40180,1.372000e-07,0.000050
m-Br,0.39,0.39,0.39,1h-data.csv,1h,0.9591,11.640,2.417000e-06,0.000719,0.26060,0.43760,1.246000e-07,0.000049
p-CN,0.66,0.66,1.00,1j-data.csv,1j,1.1010,143.900,8.246000e-07,0.000202,0.36860,5.77900,6.531000e-08,0.000016
m-NO2,0.71,0.71,0.71,1k-data.csv,1k,1.3570,75.300,9.372000e-07,0.000220,0.62590,3.55800,7.173000e-08,0.000018
p-NO2,0.78,0.79,1.27,1l-data.csv,1l,2.0000,635.200,4.714000e-07,0.000114,3.76400,35.48000,5.354000e-08,0.000013

                molecule      kOH  kH2O x 10^6  kH/Ka x 10^3       pKa
Substituent
\ce{p-OCH3}  \textbf{1c}    2.177      12.4500        4.9860  0.329569
\ce{p-CH3}   \textbf{1e}    1.564      11.9700        4.3500  0.344381
\ce{m-CH3}   \textbf{1d}    1.368       8.7760        3.5000  0.228266
\ce{H}       \textbf{1b}    1.311       6.6200        3.4100  0.252045
\ce{p-Br}    \textbf{1i}    7.726       3.2870        0.9862  0.011441
\ce{p-Cl}    \textbf{1g}    6.306       3.8220        1.1920  0.092804
\ce{m-Cl}    \textbf{1f}   10.730       2.5390        0.7592 -0.010300
\ce{m-Br}    \textbf{1h}   11.640       2.4170        0.7189  0.018136
\ce{p-CN}    \textbf{1j}  143.900       0.8246        0.2019 -0.041787
\ce{m-NO2}   \textbf{1k}   75.300       0.9372        0.2201 -0.132580
\ce{p-NO2}   \textbf{1l}  635.200       0.4714        0.1138 -0.301030

## Table 1 data

And here is the code for making the table 1 data for the handout. We will convert the values reported in table 1 to the format used in my own analysis.

in table 1 we make the following calculations.

$k_{AR}, pH=1.0$ is the first order rate constant when [H] = 0.1M.  Using the authors values for kH and Ka in table 1 we could calculate that...

$$k_{AR} = k_H \frac{[H]}{[H]+K_a}$$  

I presume that the authors obtained $K_a$ and $k_H$ values by fitting the value of $k_{AR}$ vs $pH$ in the range where the acidic reaction dominates the rate. When I use the values of $K_a$ and $k_H$ to calculate the rates at $pH = 1.0$, I get values that are 1.3 to 3-fold greater than the authors' measured $k_{AR}$ values.

From the authors table 1 the following values are calculated...

$k_{OH}$ is $k_{AR_{pH=11.5}} \times [OH]_{pH=11.5}$ or $k_{AR_{pH=11.5}}\cdot 10^{(14-11.5)}$

$k_{H2O}$ is the $k_{AR_{pH=3.8}}$ value

$\frac{k_H}{K_a}$ is the calculated using the values of $k_H$ and $K_a$ reported in table 1.

In [53]:
##############################################################
### Read data for thermodynamic parameters
##############################################################

datafile_name = "Table1data.csv"



df = pd.read_csv(github_location + datafile_name, 
             delimiter = ",", 
             skipinitialspace=True, 
             index_col="Substituent", 
             comment = "#") 
display(df)

df2 = df[["Molecule","pKa"]].copy()
df2["kOH"]=df["kAR_pS_11.5"]/(10**(-14)/10**(-11.5))
df2["kH2O x 10^6"]=df["kAR_pS_3.80"]*1E6
df2["kH/Ka x 10^3"]=df["kH"]*1E3



df2.to_csv("table1results1.csv")
df2

,Molecule,kAR_pS_11.5,kAR_pS_3.80,kAR_pS_1.0,kH,Ka,pKa
Substituent,,,,,,,
H,1b,0.00368,7.940000e-06,0.000286,0.001580,1.230,-0.09
p-OCH3,1c,0.00395,1.240000e-05,0.000422,0.002130,1.400,-0.15
m-CH3,1d,0.00641,9.180000e-06,0.000316,0.001770,1.230,-0.09
p-CH3,1e,0.00467,1.190000e-05,0.000371,0.001880,1.340,-0.13
m-Cl,1f,0.00269,2.710000e-06,0.000078,0.000533,0.976,0.01
p-Cl,1g,0.01610,3.990000e-06,0.000119,0.000726,1.080,-0.03
m-Br,1h,0.03120,2.640000e-06,0.000075,0.000495,0.983,0.01
p-Br,1i,0.02000,3.440000e-06,0.000105,0.000652,1.060,-0.03
p-CN,1j,0.32100,9.500000e-07,0.000022,0.000155,0.880,0.06
m-NO2,1k,0.15800,9.950000e-07,0.000024,0.000180,0.868,0.06
p-NO2,1l,1.19000,6.100000e-07,0.000012,NaN,NaN,NaN

            Molecule   pKa         kOH  kH2O x 10^6  kH/Ka x 10^3
Substituent
H                 1b -0.09    1.163718        7.940         1.580
p-OCH3            1c -0.15    1.249100       12.400         2.130
m-CH3             1d -0.09    2.027020        9.180         1.770
p-CH3             1e -0.13    1.476784       11.900         1.880
m-Cl              1f  0.01    0.850653        2.710         0.533
p-Cl              1g -0.03    5.091267        3.990         0.726
m-Br              1h  0.01    9.866306        2.640         0.495
p-Br              1i -0.03    6.324555        3.440         0.652
p-CN              1j  0.06  101.509113        0.950         0.155
m-NO2             1k  0.06   49.963987        0.995         0.180
p-NO2             1l   NaN  376.311042        0.610           NaN