In [1]:
import numpy as np
import pandas as pd

import uncertainties as un
import uncertainties.unumpy as unp


df = pd.read_csv('TaftData1952.csv',
                 delimiter = ",", 
                 skipinitialspace=True, 
                 index_col="Sub", 
                 comment = "#")

In [2]:
n = df['base ratio']
e = df['base error']

p = unp.uarray(n, e)  # Create an array of uncertainties

#a = 10**p * 43E-6  # Convert to an array of values with uncertainties
a = 10**p * 0.112  # Convert to an array of values with uncertainties

unp.log10(a/a[1])

array([2.46+/-0.14422205101855953, 0.0+/-8.881784197001253e-18,
       -0.31+/-0.09433981132056603, -0.64+/-0.12041594578792295,
       -0.71+/-0.12041594578792295, -0.55+/-0.08246211251235322,
       nan+/-nan, 0.17+/-0.08544003745317533,
       -0.13999999999999996+/-0.08062257748298549,
       -0.4000000000000001+/-0.08246211251235322,
       -0.94+/-0.1131370849898476, nan+/-nan, -1.24+/-0.09999999999999999,
       -1.13+/-nan, nan+/-nan, -0.93+/-nan, -1.42+/-nan,
       -2.38+/-0.14422205101855956, -1.09+/-nan,
       -2.7+/-0.09999999999999999, -0.75+/-0.12041594578792295, nan+/-nan,
       -1.06+/-0.08944271909999159, nan+/-nan], dtype=object)

In [31]:
for i in a:
#    print(f"{i.n:.3e} Â± {unp.std_devs(i):.3e}")
    print(f"{i:.3e}")

(3.230+/-0.893)e+01
(1.120+/-0.206)e-01
(5.486+/-0.632)e-02
(2.566+/-0.532)e-02
(2.184+/-0.453)e-02
(3.157+/-0.145)e-02
nan+/-nan
(1.657+/-0.114)e-01
(8.114+/-0.187)e-02
(4.459+/-0.205)e-02
(1.286+/-0.237)e-02
nan+/-nan
(6.445+/-0.890)e-03
(8.303+/-nan)e-03
nan+/-nan
(1.316+/-nan)e-02
(4.258+/-nan)e-03
(4.669+/-1.290)e-04
(9.104+/-nan)e-03
(2.235+/-0.309)e-04
(1.992+/-0.413)e-02
nan+/-nan
(9.755+/-0.898)e-03
nan+/-nan

In [9]:
df

               acid ratio  acid Error  base ratio  base error
Sub
H                    1.24        0.09        2.46        0.12
CH3                  0.00        0.06        0.00        0.08
C2H5                -0.07        0.02       -0.31        0.05
n-C3H7              -0.36        0.02       -0.64        0.09
n-C4H9              -0.39        0.05       -0.71        0.09
n-C5H11             -0.40        0.07       -0.55        0.02
i-C5H11             -0.35        0.01         NaN         NaN
CH2C6C5             -0.38        0.04        0.17        0.03
CH2CH2C6H5          -0.43        0.09       -0.14        0.01
CH2CH2CH2C6H5       -0.45        0.06       -0.40        0.02
i-C3H7              -0.47        0.06       -0.94        0.08
c-C6H11             -0.79        0.17         NaN         NaN
i-C4H9              -0.93        0.10       -1.24        0.06
CH2-c-C6H11         -0.98        0.05       -1.13         NaN
CH(CH3)(C2H5)       -1.13        0.16         NaN         NaN
CHMePh              -1.19        0.07       -0.93         NaN
CHPhEt              -1.50        0.10       -1.42         NaN
t-C4H9              -1.54        0.02       -2.38        0.12
CHPh2               -1.76        0.15       -1.09         NaN
CHEt2               -1.98        0.28       -2.70        0.06
CHCHPh              -1.99         NaN       -0.75        0.09
CCl3                -2.06         NaN         NaN         NaN
C6H5                -2.55        0.08       -1.06        0.04
CH2Cl               -0.19        0.05         NaN         NaN

In [10]:
import numpy as np
import pandas as pd

import uncertainties as un
import uncertainties.unumpy as unp


df = pd.read_csv('TaftData1952rates.csv',
                 delimiter = ",", 
                 skipinitialspace=True, 
                 index_col="Sub", 
                 comment = "#") 

df

               acid rate (s-1)      acid err  base rate (M-1s-1)  base err
Sub
H                 7.473000e-04  1.549000e-04            32.30000  8.930000
CH3               4.300000e-05  5.941000e-06             0.11200  0.020600
C2H5              3.660000e-05  1.685000e-06             0.05486  0.006320
n-C3H7            1.877000e-05  8.644000e-07             0.02566  0.005320
n-C4H9            1.752000e-05  2.017000e-06             0.02184  0.004530
n-C5H11           1.712000e-05  2.759000e-06             0.03157  0.001450
i-C5H11           1.921000e-05  4.423000e-07                 NaN       NaN
CH2C6C5           1.793000e-05  1.651000e-06             0.16570  0.011400
CH2CH2C6H5        1.598000e-05  3.311000e-06             0.08114  0.001870
CH2CH2CH2C6H5     1.526000e-05  2.108000e-06             0.04459  0.002050
i-C3H7            1.457000e-05  2.013000e-06             0.01286  0.002370
c-C6H11           6.974000e-06  2.730000e-06                 NaN       NaN
i-C4H9            5.052000e-06  1.163000e-06             0.00645  0.000890
CH2-c-C6H11       4.503000e-06  5.184000e-07             0.00833       NaN
CH(CH3)(C2H5)     3.188000e-06  1.174000e-06                 NaN       NaN
CHMePh            2.776000e-06  4.475000e-07             0.01316       NaN
CHPhEt            1.360000e-06  3.131000e-07             0.00426       NaN
t-C4H9            1.240000e-06  5.711000e-08             0.00047  0.000130
CHPh2             7.473000e-07  2.581000e-07             0.00910       NaN
CHEt2             4.503000e-07  2.903000e-07             0.00022  0.000031
CHCHPh            4.400000e-07           NaN             0.01992  0.004130
CCl3              3.745000e-07           NaN                 NaN       NaN
C6H5              1.212000e-07  2.232000e-08             0.00976  0.000900
CH2Cl             2.776000e-05  3.196000e-06                 NaN       NaN

In [17]:
n = df['acid rate (s-1)']
e = df['acid err']

n = df['base rate (M-1s-1)']
e = df['base err']

p = unp.uarray(n, e)  # Create an array of uncertainties
print(p)
a = p  # Convert to an array of values with uncertainties

unp.log10(a/a[1])

[32.3+/-8.93 0.112+/-0.0206 0.05486+/-0.00632 0.02566+/-0.00532
 0.02184+/-0.00453 0.03157+/-0.00145 nan+/-nan 0.1657+/-0.0114
 0.08114+/-0.00187 0.04459+/-0.00205 0.01286+/-0.00237 nan+/-nan
 0.00645+/-0.00089 0.00833+/-nan nan+/-nan 0.01316+/-nan 0.00426+/-nan
 0.00047+/-0.00013 0.0091+/-nan 0.00022+/-3.1e-05 0.01992+/-0.00413
 nan+/-nan 0.00976+/-0.0009 nan+/-nan]

array([2.459984499660921+/-0.14421304325680248,
       0.0+/-9.14823772291129e-18,
       -0.30996221940167096+/-0.09425420707880594,
       -0.6399613706312719+/-0.12036620976318298,
       -0.709965388637482+/-0.12039577775797462,
       -0.5499434407779643+/-0.08233203420269784, nan+/-nan,
       0.17010448574915504+/-0.08528445271108803,
       -0.13998301930187418+/-0.08050379474319898,
       -0.3999805503205744+/-0.08233674528621006,
       -0.9399770540819783+/-0.11307797450459564, nan+/-nan,
       -1.239658308034914+/-0.09985887493741617, -1.128573021263394+/-nan,
       nan+/-nan, -0.929962133392245+/-nan, -1.4198084235674626+/-nan,
       -2.377120164734464+/-0.1442583013639894, -1.090176630349088+/-nan,
       -2.7067953418479753+/-0.10062622010272856,
       -0.7499286885825017+/-0.12036709958352657, nan+/-nan,
       -1.0597682050034898+/-0.08935600038678577, nan+/-nan], dtype=object)